### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by tuntunpandit** [raghav007bisht/Intrusion-Detection-System-IDS-v5.0#1]
![screenshot from 2018-03-21 21-20-46](https://user-images.githubusercontent.com/31283703/37708922-dbe602aa-2cde-11e8-8723-c3f161aacc2f.png)

**Comment by h4ck3d-by-r46h4v** [comment]
Hi @Mr-Tuntun thanks to this issue.
Turns out to be forward slash (\) was missing before "@gmail" in line 53.
Bug has been fixed and committed. 

Thanks Again.

**Comment by tuntunpandit** [comment]
Hello , Raghav
                   I am a student from Lovely Professional University, and
I am given a project on IDS. So, i was wondering if you could help me in
making this project I would be very grateful.
                   This  is my whatsapp no. 9041531078 . Please send
response.

  Thanks in advance.

<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>
